language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - coverage run --timid --source=. tests/all_test.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
